### PR TITLE
removes whitelist from most of the donator items

### PR DESCRIPTION
**Pull request by thestubborn**
i stripped most of the donator whitelist things, some i left (like a lot of the toy guns, and A FUCKING DARKSABER TOY, WHAT??) but, a good % of the clothing's been dekeyed, hence the branch name white apartheid.

i tested it, it seemed to work fine, if anything's a little no bueno/should be role restricted, simply say

### CODE REVIEW

**Comment by thestubborn** [comment]
...oh god it fucked didnt it

**Comment by thestubborn** [comment]
right, i fixed it...i think, i meant to have the loadout stuff be another pr, but...its been done

**Comment by thestubborn** [comment]
wait nope, think i uhh....got rid of the other loadout stuff

**Comment by Useroth** [comment]
To be honest, at this point it might be better PRed to this repo, https://github.com/Skyrat-SS13/Skyrat13 , and in a modular fashion.
And by modular, I mean making a new file there in `modular_skyrat/code/modules/client/loadout/__donator.dm` (you might need to create the dirs and the new file itself)
with for example
```
/datum/gear/russianflask
	ckeywhitelist = null
```
in it, and also analogically for all other items you'd un-whitelist

**Comment by thestubborn** [comment]
...oh no

**Comment by improvedname** [comment]
Remove the carrot satchel/plushie/cloak

**Comment by thestubborn** [comment]
wait why?
carrot stuff good!!
(and may be one of the main reasons i did this but ignore that)

**Comment by thestubborn** [comment]
by which I mean
i am willing to add a cost to the carrot stuff
but not remove them

**Review by Useroth — CHANGES_REQUESTED** [review]
Leave Hyena's carrot stuff whitelisted.

**Comment by thestubborn** [comment]
reece complained about his stuff being dewhitelisted, i still kept it
why should i do the same for the carrot stuff?
its good for people who play bunny rabbits and horses

**Comment by improvedname** [comment]
image

**Comment by thestubborn** [comment]
in my defence, i was bluffing, but oh well
:(

**Pull request closed without merging**
